name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - numpy
  - pandas
  - xarray
  - geopandas
  - cdsapi
  - s3fs
  - matplotlib
  - cartopy
  - rioxarray
  - rasterio
  - concurrent
  - datetime
  - PIL
  - IPython
  - pyogrio
  - requests
  - geoviews
  - holoviews
  - bokeh
  - shapely
  - UserDefined
  - metpy
  - tropycal
  - CPyS
  - TempestExtremes
